openapi: 3.0.0
info:
  title: Keeper API
  version: 1.0.0
paths:
  /file:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostFileRequest'
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostFileResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'  
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'  
    get:
      summary: Get file data
      parameters:
        - name: fileID
          in: query
          required: true
          description: The ID of the file to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: File retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'  
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'  
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

components:
  schemas:
    PostFileRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
        location:
          type: string
    PostFileResponse:
      type: object
      properties:
        fileID:
          type: string
          format: uuid
    GetFileResponse:
      type: object
      properties:
        fileData:
          type: string
        fileHash:
          type: string
    ApiErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string